[component]
structures = [ "content_blocks" ]
label = "Blog"
description = "Blog Section with heading, a image, a description and a link"
icon = "wysiwyg"
tags = ["Content"]

[props]
title = "Blog"
description_html = "Posts from Jessica Brentnall on tech, management and life."
link_url = "/blog"
show_posts = true